# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_GrantedWish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wisher', to='login_registration_app.User')),
                ('usersWishes', models.ManyToManyField(related_name='grantsWishes', to='login_registration_app.User')),
            ],
        ),
    ]
